version: '3'
services:
  db:
    restart: always
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -ppassword | grep 'mysqld is alive'"]
      interval: 15s
      timeout: 5s
      retries: 6
  app:
    restart: always
    build: .
    command: rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
volumes:
  mysql-db:
  bundle:
